### ISSUE TITLE
PHPFlasher needs a new logo

### ISSUE THREAD

**Issue by yoeunes** [php-flasher/php-flasher.github.io#18]
The current @php-flasher logo was created with a logo generator.

<p align="center" >
    <img src="https://user-images.githubusercontent.com/10859693/173875730-13eb3243-6324-4e4f-a8e9-c4358cb0d4b6.png" width="300" />
</p>

I would like to change the logo with a more meaningful one.

**Contributions are welcome and will be fully credited.**

**Comment by ash-jc-allen** [comment]
Hey @yoeunes! If you drop me an email (mail@ashallendesign.co.uk), I might be able to sort a logo out for you 😄

**Comment by LucasStorm** [comment]
Hey, i'm not a designer, but i made these. Hope its help you.

![Azul Moderno Gradiente Saúde e Médico Logotipo](https://user-images.githubusercontent.com/80225404/194615963-c479c84f-fe2b-4b19-aded-ac40788f9dfa.png)

![Azul Moderno Gradiente Saúde e Médico Logotipo (1)](https://user-images.githubusercontent.com/80225404/194615971-aa09342c-8980-40ce-b34f-b1bd1b9fdd87.png)

**Comment by yoeunes** [comment]
Hey @LucasStorm and @ash-jc-allen,

I wanted to take a moment to express my gratitude for both of your contributions to the PHPFlasher. 

Lucas, thank you for your willingness to contribute and for taking the time to create a logo design for us.

Ash, thank you for creating the final logo that we ended up choosing for the project. 

Both of your efforts are greatly appreciated, and we would like to include both of you in our list of contributors for your time and dedication. 

Thanks again for your support ♥️🙏.
